#create a project
POST http://localhost:4500/students
Content-Type: application/json

{
    "studentname": "Milla jesso",
    "classroom": "4 west",
    "feebalance": "444444444444"
  
}



### GET ALL PROJECTS
GET http://localhost:4500/students



### GET ONE PROJECT
GET http://localhost:4500/students/744e2284-82d4-4470-b542-e8d0b92e0bae 


### UPDATING PROJECT
PUT http://localhost:4500/students/2dbc5a9c-1e27-480e-9aa3-3d78c8fa0dfb
Content-Type: application/json

{
    "feebalance": "48"
}

###delete
DELETE http://localhost:4500/students/744e2284-82d4-4470-b542-e8d0b92e0bae 



