#create a project
POST http://localhost:4500/students

{
    "studentname": "Milla",
    "classroom": "4 east",
    "feebalance": "58858"
  
}



### GET ALL PROJECTS
GET http://localhost:4500/students



### GET ONE PROJECT
GET http://localhost:students/projects/0c0765dd-6397-41b4-a001-f7bd304499c9


### UPDATING PROJECT
PUT http://localhost:4500/students/0c0765dd-6397-41b4-a001-f7bd304499c9

I

{
    "feebalance": "45448",
    
}

###delete
DELETE http://localhost:4500/students/00e7d3cf-2031-4b35-bdc7-1fed12541c77


